name: Dependabot Auto-merge

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "LICENCE"
      - "CODEOWNERS"
      - ".gitignore"
      - ".github/workflows/build-pr.yaml"
      - ".github/workflows/deploy.yaml"
      - ".github/workflows/manual-deploy.yaml"
      - ".github/workflows/playwright.yaml"
      - ".github/workflows/security.yaml"
      - ".github/dependabot.yaml"
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * MON-FRI" # 9:00 AM GMT+2 (7:00 AM UTC)

permissions:
  contents: write
  pull-requests: write
  checks: read
  statuses: read

jobs:
  dependabot-automerge:
    uses: navikt/mob-gha-workflows/.github/workflows/dependabot-automerge.yaml@main
    secrets: inherit
